version: '3.8'

services:
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 10:200 rwm'
    expose:
      - 1080
    environment:
      - WARP_SLEEP=2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - warp-data:/var/lib/cloudflare-warp

  app:
    build: .
    container_name: fastapi-app
    depends_on:
      - warp
    environment:
      - HTTP_PROXY=socks5h://warp:1080
      - HTTPS_PROXY=socks5h://warp:1080
    ports:
      - "8888:8888"
    cap_add:
      - NET_ADMIN

volumes:
  warp-data:
